function fcnalphaplot(X1, Y1, Y2)
%CREATEFIGURE(X1,Y1,X2,Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 02-Jul-2009 16:25:11

% Copyright 2009 - 2011 MathWorks, Inc.

X2 = X1;
Y2 = ones(size(X1))*Y2;

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'XTickLabel',['Jul-07';'Sep-07';'Nov-07';...
    'Jan-08';'Mar-08';'May-08'],...
    'XTick',1:2:12);
% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[1 12]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.35 0.6501]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'MarkerFaceColor',[0 0 1],'Marker','o',...
    'LineStyle',':',...
    'DisplayName','Monthly');

% Create ylabel
ylabel('\alpha');

% Create plot
plot(X2,Y2,'Parent',axes1,'LineWidth',2,...
    'Color',[0.8471 0.1608 0],...
    'DisplayName','Overall');

% Create legend
legend(axes1,'show');

